services:
  api:
    build:
      context: .
      args:
        LOG_DIR: ${LOG_DIR}
    depends_on:
      - cache
    env_file:
      - .env
    volumes:
      - ./:/app
      - /app/node_modules
      - ${LOG_DIR}:/app/logs
    restart: unless-stopped
    command: npm run start
    ports:
        - "127.0.0.1:${PORT}:${PORT}"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:${PORT}/ >/dev/null 2>&1 || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s

  cache:
    image: redis:7-alpine
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 5s



